### PR TITLE
Missing dependency for Voyage-Model-Tests

### PR DESCRIPTION
**Pull request by demarey**

### CODE REVIEW

**Comment by tinchodias** [comment]
Ah, I didn't know this was reported. I also observed recently that the test objects in Voyage-Model-Tests depend on -JSON package.

**Comment by noha** [comment]
Yes, it is a problem. Depending on JSON with the model tests is not a good idea. Solving that with method extensions would introduce the same thing. So summing up the problems tells me that those classes are in the wrong place

**Comment by noha** [comment]
Ok, looking at it again the problem is that all classes in Voyage-JSON-magritte do not belong in a package called *JSON* that is the problem. If they were factored out the json and the test package could depend on that new package and the problem would be solved I guess

**Comment by noha** [comment]
I close it for now. To solve this we need to make more and better changes than the ones in this pull request

**Pull request closed without merging**
