### PR TITLE
Add VOCollector

### PR DESCRIPTION
**Pull request by tinchodias**
Add VOCollector, who knows how to traverse an object and its referenced objects (VODescription references), and selectively collect them.

### CODE REVIEW

**Comment by tinchodias** [comment]
I'd like to merge this change. It is part of a bigger change to solve #13 , which is ready to push.

**Comment by tinchodias** [comment]
Buh, despite travis build result, the PR's working. All tests fail in Pharo 6 due to some issue with Magritte that I didin't investigate yet.

**Comment by estebanlm** [comment]
this is because we removed pharo5 from the #metacelloPlatformAttributes (it was time), and now everything that is not explicitly marked “pharo6” or “common” will fail… magritte and seaside (and I guess grease) have not released versions for pharo6. 

magritte3 version for pharo6 should be just same version as pharo5 (no changes there)… update configuration is needed. 

Esteban

**Comment by tinchodias** [comment]
BaselineOfVoyage requires ConfigurationOfMagritte3/stable, which is:
```
stable: spec 
	<symbolicVersion: #stable>
	
	spec for: #'common' version: #'release3.5'
```
then, should we point explicitly  to `release3.5`?

**Comment by tinchodias** [comment]
I talked too fast

**Comment by tinchodias** [comment]
Anyway, the fact that Magritte3 has an issue with Pharo6 doesn't impede that this issue is reviewed. So you are welcome ;-) :-D

**Comment by tinchodias** [comment]
Great! Magritte3 works again.

**Comment by noha** [comment]
@tinchodias Whenever you see a symbolic version in voyage, mongo, etc, please remove it. We don't that ;)

**Comment by estebanlm** [comment]
yeah, but dependences do it :(

**Pull request merged**
