### PR TITLE
New update-if-current option

### PR DESCRIPTION
**Pull request by tinchodias**
New update-if-current feature, to ensure an object is current in a save operation.

# API

VOMongoRepository has now:

- **#saveEnsuringCurrent:** and **#save: id:ensuringCurrent:**. When save-if-current enabled, update the object and check if the object is still current in the database; else, signal a **VOMongoNotCurrentError**.
- **#ensuringCurrentOnSave:**. It specifies the default option for #save: operations (default: false)
- **#wireProtocolEnabled:**. When true, the repository uses the old-style implementation for #save: operations; when false, the repository uses the [new Write Concerns](https://docs.mongodb.com/manual/release-notes/2.6-compatibility/#write-method-acknowledgements), introduced in mongodb 2.6. (default: true). 

# Notes
- The use of Write Concerns (i.e. #isWireProtocolEnabled is false) **require mongodb>=2.6**.

- There are no code changes on inserts or any other operation... only on update. 

- By default, repository's behavior is unchanged (performance too).

# Tests

- The **Voyage-Mongo-Tests** package has now **VOMongoWireProtocolTest** and **VOMongoCommandTest**. Both are subclasses of VOMongoTest, which is now abstract since the subclasses cover all possiblities.
- New **Voyage-Mongo-MultipleImageTests** package with the class **VOUpdateIfCurrentTest**. The test case belongs to a separete package because require ImageWorker, a project must be loaded with a special Baseline's group named 'mongo tests multiple'. Snippet:

```
Metacello new 
    repository: 'github://pharo-nosql/voyage/mc';
    baseline: 'Voyage';
    load: 'mongo tests multiple'.
```

### CODE REVIEW

**Comment by tinchodias** [comment]
@noha thanks for the review. I didn't notice it, maybe it's noise introduced by one of my merges. I'm on it now.

**Comment by tinchodias** [comment]
Do you think it is ready to merge now?

**Comment by noha** [comment]
I merged this now. I still think we should address the fact that instead of using methods with ifTrue:ifFalse: we could make the write strategy an object. Are there any reasons why you did it this way?

**Comment by tinchodias** [comment]
@noha Initially I created a strategy but afterwards refactored as boolean+if... I didn't like that the only behavior in the strategy hierarchy (3 classes, with the abstract superclass) was a kind of double-dispatch method.

**Pull request merged**
