### PR TITLE
Replica set support (version 2)

### PR DESCRIPTION
**Pull request by tinchodias**
# In a few snippets

"It is backward compatible, and works as before:"
repository := VOMongoRepository host: 'localhost' port: 27017 database: 'blah'.

"Simple to enable replication (mongodb replica set must be set up manually, i.e. in command line)"
repository := VOMongoRepository host: 'localhost' port: 27017 database: 'blah'.
repository enableReplication.

"Initialize with a list of mongo urls - this actually needs 'another turn of the screw'"
repository := VOMongoRepository mongoUrls: {'localhost:27031' asMongoUrl. 'localhost:27032' asMongoUrl} database: 'blah'.

# Voyage

- VOMongoRepositoryResolver has 2 new friends:
  - an execution strategy. Implemented in VOMongoExecuteStrategy, it's an object to execute persistence operations, retry on fail (centralize error handling).
  - a strategy to get what's the mongodb to interact with. Implemented in the VOMongoUrlResolver hierarchy, where one subclass implements classical no-replication behavior, and the other subclass implements the new replication support.

- Use ZnUrl to represent mongodb urls (host:port) in a more compact way.

- Many new tests

# MongoTalk

- has new replication API, and tests (that run only if testing scenario was set up, and don't make noise if it wasn't).
- added 'scripts', a directory with bash scripts to set up replication testing scenario. The guide to use them is in  MongoReplicationTestResources>>_manual_set_up_
- add Mongo>>lastError, reify the answer as MongoLastError (+tests). No impact in old users.
- check for query errors. Mongo>>query: and queryOne: check whether the result is "$err" (voyage was doing it but it fits better here). Created MongoQueryError to represent it. This change in error handling impacts direct users of Mongotalk (I mean, not for indirect users through Voyage-Mongo).

---

In this voyage's branch, I've temporarily overwritten the baseline of voyage to use my mongotalk's branch:
https://github.com/pharo-nosql/mongotalk/compare/master...tinchodias:replicaSetSupport2

Please, read MongoReplicationTestResources>>_manual_set_up_ and run the tests. 

Thanks in advance.

### CODE REVIEW

**Comment by tinchodias** [comment]
@zecke

**Comment by tinchodias** [comment]
I should say more about the tests. Besides I tried to cover most important cases, I also wanted clear tests and scenario so they can communicate the readers what is the replication support about. 

You can find the tests in "Voyage-Mongo-Tests-Replication"; I recommend to follow path: 

1. set up testing scenario by following MongoReplicationTestResources>>_manual_set_up_
2. start by VOMongoReplicationBasicTest,
3. continue with VOMongoReplicationStepDownScenarioTest, specially reading the method #testOn:acceptableTimeToFail:

I would appreciate your feedback, specially @zecke!

**Comment by tinchodias** [comment]
Hi again: 
I'm sorry, maybe it's too hard to review this PR since the commits show my development path to find a right solution (IMO) at the end, and that's not a direct path + some of the commits have not good descriptions.

I could rebase the PR changes and create a few more meaningful commits. I could have done it in first place but I thought it was good idea to receive a first-glance discussion on my final code. I wanted to know if there is something important that escaped to my understanding. 

Please tell me if you prefer that I first rebase and create better commits before we start discussing.

**Comment by estebanlm** [comment]
now is having conflicts :( 
the problems of working with old filetree format, but we need to carry it for some time still. 
give me a new merge without conflicts and I will accept the PR :)

**Comment by zecke** [comment]
> On 08 Jul 2016, at 10:06, Esteban Lorenzano <notifications@github.com> wrote:
> 
> now is having conflicts :( 
> the problems of working with old filetree format, but we need to carry it for some time still. 
> give me a new merge without conflicts and I will accept the PR :)

please rebase/squash/fix first and I will make a proper review. A simple commit series makes it easier for me to make it work with an older Voyage (if I decide that I want to go down that road).

**Comment by zecke** [comment]
With my C/git hat on I would like to see:

* Direct MongoCollection creation and removal of the "cache" for >>#collectionAt: in a separate PR. Is there any performance impact for that? We create a lot more temporary objects now?

* the execution strategy (and the removal of the catch all/repeat until stack is full) in a separate commit as well.

* getLastError() on insert. Is this for _all_ users or only if replication is on? I assume some users might not like the extra roundtrip.

**Comment by tinchodias** [comment]
On Fri, Jul 8, 2016 at 5:20 PM, Holger Freyther <notifications@github.com>
wrote:

> With my C/git hat on I would like to see:
>
Thanks for pointing out.

>
>    -
>
>    Direct MongoCollection creation and removal of the "cache" for
>    >>#collectionAt: in a separate PR. Is there any performance impact for
>    that? We create a lot more temporary objects now?
>
> Right, that's not needed. I didn't profile voyage, but I know from
profiling in other projects that creation of simple objects is faster than
we believe, compared with other operations that we don't suspect of, such
as creation of dictionaries. Voyage operations create dictionaries like in
this snippet, and that's way slower:

{[{ 'update'->1. '#version'->2 } asDictionary ] bench.
[ MongoCollection database: nil name: 'name' ] bench.}
"in my old computer ---> #('226,906 per second' '5,929,453 per second')"


>    -
>
>    the execution strategy (and the removal of the catch all/repeat until
>    stack is full) in a separate commit as well.
>
> Ok.

>
>    -
>
>    getLastError() on insert. Is this for *all* users or only if
>    replication is on? I assume some users might not like the extra roundtrip.
>
> Surprisingly (to me, at least), operations fail silently when a node
stepped down... IMO that's not acceptable, is it? Then, I added a
getLastError check after operations to detect that, but I wanted to do it
only when the replication is on, and I forgot to do it only in that case.

Ok, I will create new PRs, thanks,.

**Comment by tinchodias** [comment]
I created [2 PR in mongotalk](https://github.com/pharo-nosql/mongotalk/pulls).

**Comment by tinchodias** [comment]
Last week I created [a new PR](https://github.com/pharo-nosql/voyage/pull/47). 
I think esteban is on vacations, but maybe other collaborators can take look it.

**Comment by tinchodias** [comment]
If #54 is merged, then I only need to fix a last point that @zecke discovered: "getLastError() on insert. Is this for *all* users...".

**Comment by tinchodias** [comment]
Please review #55

**Pull request closed without merging**
